# -*- coding: utf-8 -*-
__author__ = 'Bai Bo and Jia Chen'
# Form implementation generated from reading ui file 'mnist_gui_design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class EmittingStream(QtCore.QObject):
    textWritten = QtCore.pyqtSignal(str)  # 定义一个发送str的信号

    def write(self, text):
        self.textWritten.emit(str(text))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 868)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView_ori_0 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_ori_0.setGeometry(QtCore.QRect(40, 180, 145, 145))
        self.graphicsView_ori_0.setObjectName("graphicsView_ori_0")
        self.Combo_feature = QtWidgets.QComboBox(self.centralwidget)
        self.Combo_feature.setGeometry(QtCore.QRect(150, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(13)
        self.Combo_feature.setFont(font)
        self.Combo_feature.setObjectName("Combo_feature")
        self.Combo_feature.addItem("")
        self.Combo_feature.addItem("")
        self.Combo_feature.addItem("")
        self.Combo_feature.addItem("")
        self.Combo_feature.addItem("")
        self.Combo_feature.addItem("")
        self.Label_feature = QtWidgets.QLabel(self.centralwidget)
        self.Label_feature.setGeometry(QtCore.QRect(40, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(15)
        self.Label_feature.setFont(font)
        self.Label_feature.setTextFormat(QtCore.Qt.AutoText)
        self.Label_feature.setObjectName("Label_feature")
        self.graphicsView_new_0 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_new_0.setGeometry(QtCore.QRect(440, 180, 145, 145))
        self.graphicsView_new_0.setObjectName("graphicsView_new_0")
        self.Label_model = QtWidgets.QLabel(self.centralwidget)
        self.Label_model.setGeometry(QtCore.QRect(420, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(15)
        self.Label_model.setFont(font)
        self.Label_model.setTextFormat(QtCore.Qt.AutoText)
        self.Label_model.setObjectName("Label_model")
        self.Combo_model = QtWidgets.QComboBox(self.centralwidget)
        self.Combo_model.setGeometry(QtCore.QRect(530, 100, 200, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        self.Combo_model.setFont(font)
        self.Combo_model.setObjectName("Combo_model")
        self.Combo_model.addItem("")
        self.Combo_model.addItem("")
        self.Combo_model.addItem("")
        self.Label_1 = QtWidgets.QLabel(self.centralwidget)
        self.Label_1.setGeometry(QtCore.QRect(40, 140, 111, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(15)
        self.Label_1.setFont(font)
        self.Label_1.setTextFormat(QtCore.Qt.AutoText)
        self.Label_1.setObjectName("Label_1")
        self.Label_2 = QtWidgets.QLabel(self.centralwidget)
        self.Label_2.setGeometry(QtCore.QRect(440, 140, 161, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(15)
        self.Label_2.setFont(font)
        self.Label_2.setTextFormat(QtCore.Qt.AutoText)
        self.Label_2.setObjectName("Label_2")
        self.Label_3 = QtWidgets.QLabel(self.centralwidget)
        self.Label_3.setGeometry(QtCore.QRect(40, 480, 171, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(15)
        self.Label_3.setFont(font)
        self.Label_3.setTextFormat(QtCore.Qt.AutoText)
        self.Label_3.setObjectName("Label_3")
        self.Label_4 = QtWidgets.QLabel(self.centralwidget)
        self.Label_4.setGeometry(QtCore.QRect(40, 730, 701, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(15)
        self.Label_4.setFont(font)
        self.Label_4.setTextFormat(QtCore.Qt.AutoText)
        self.Label_4.setObjectName("Label_4")
        self.Label_5 = QtWidgets.QLabel(self.centralwidget)
        self.Label_5.setGeometry(QtCore.QRect(50, 750, 841, 111))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.Label_5.setFont(font)
        self.Label_5.setTextFormat(QtCore.Qt.AutoText)
        self.Label_5.setObjectName("Label_5")
        self.textEdit_trainnum = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_trainnum.setGeometry(QtCore.QRect(780, 200, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_trainnum.setFont(font)
        self.textEdit_trainnum.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textEdit_trainnum.setObjectName("textEdit_trainnum")
        self.Label_6 = QtWidgets.QLabel(self.centralwidget)
        self.Label_6.setGeometry(QtCore.QRect(780, 170, 171, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(15)
        self.Label_6.setFont(font)
        self.Label_6.setTextFormat(QtCore.Qt.AutoText)
        self.Label_6.setObjectName("Label_6")
        self.Label_7 = QtWidgets.QLabel(self.centralwidget)
        self.Label_7.setGeometry(QtCore.QRect(780, 270, 171, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(15)
        self.Label_7.setFont(font)
        self.Label_7.setTextFormat(QtCore.Qt.AutoText)
        self.Label_7.setObjectName("Label_7")
        self.textEdit_testnum = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_testnum.setGeometry(QtCore.QRect(780, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_testnum.setFont(font)
        self.textEdit_testnum.setObjectName("textEdit_testnum")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(780, 370, 101, 41))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.Label_name = QtWidgets.QLabel(self.centralwidget)
        self.Label_name.setGeometry(QtCore.QRect(40, 20, 281, 41))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(25)
        self.Label_name.setFont(font)
        self.Label_name.setTextFormat(QtCore.Qt.AutoText)
        self.Label_name.setObjectName("Label_name")
        self.graphicsView_ori_1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_ori_1.setGeometry(QtCore.QRect(190, 180, 145, 145))
        self.graphicsView_ori_1.setObjectName("graphicsView_ori_1")
        self.graphicsView_ori_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_ori_2.setGeometry(QtCore.QRect(40, 330, 145, 145))
        self.graphicsView_ori_2.setObjectName("graphicsView_ori_2")
        self.graphicsView_ori_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_ori_3.setGeometry(QtCore.QRect(190, 330, 145, 145))
        self.graphicsView_ori_3.setObjectName("graphicsView_ori_3")
        self.graphicsView_new_1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_new_1.setGeometry(QtCore.QRect(590, 180, 145, 145))
        self.graphicsView_new_1.setObjectName("graphicsView_new_1")
        self.graphicsView_new_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_new_2.setGeometry(QtCore.QRect(440, 330, 145, 145))
        self.graphicsView_new_2.setObjectName("graphicsView_new_2")
        self.graphicsView_new_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_new_3.setGeometry(QtCore.QRect(590, 330, 145, 145))
        self.graphicsView_new_3.setObjectName("graphicsView_new_3")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 520, 691, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.Label_author = QtWidgets.QLabel(self.centralwidget)
        self.Label_author.setGeometry(QtCore.QRect(800, 610, 131, 111))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Label_author.setFont(font)
        self.Label_author.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label_author.setObjectName("Label_author")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 写入控制台信息
        sys.stdout = EmittingStream(textWritten=self.outputWritten)
        sys.stderr = EmittingStream(textWritten=self.outputWritten)

    def outputWritten(self, text):
        cursor = self.textEdit.textCursor()
        cursor.movePosition(QtGui.QTextCursor.End)
        cursor.insertText(text)
        self.textEdit.setTextCursor(cursor)
        self.textEdit.ensureCursorVisible()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于模式识别的图像识别系统"))
        self.Combo_feature.setItemText(0, _translate("MainWindow", "轮廓特征"))
        self.Combo_feature.setItemText(1, _translate("MainWindow", "偏移校正"))
        self.Combo_feature.setItemText(2, _translate("MainWindow", "图像锐化"))
        self.Combo_feature.setItemText(3, _translate("MainWindow", "HOG特征"))
        self.Combo_feature.setItemText(4, _translate("MainWindow", "池化特征"))
        self.Combo_feature.setItemText(5, _translate("MainWindow", "原始图像"))
        self.Label_feature.setText(_translate("MainWindow", "特征选择"))
        self.Label_model.setText(_translate("MainWindow", "模型选择"))
        self.Combo_model.setItemText(0, _translate("MainWindow", "KNN"))
        self.Combo_model.setItemText(1, _translate("MainWindow", "Softmax Regression"))
        self.Combo_model.setItemText(2, _translate("MainWindow", "CNN"))
        self.Label_1.setText(_translate("MainWindow", "原始图像"))
        self.Label_2.setText(_translate("MainWindow", "特征提取结果"))
        self.Label_3.setText(_translate("MainWindow", "模型输出结果"))
        self.Label_4.setText(_translate("MainWindow", "可视化信息查看步骤"))
        self.Label_5.setText(_translate("MainWindow", "1.进入程序当前目录下\\tmp文件夹，依据不同分类模型选取不同子目录，如\\mnist_cnn_logs，\n"
"依据不同特征选取不同.bat文件，如原始图像.bat，双击运行，保持命令窗口开启\n"
"2.打开浏览器进入http://localhost:6006\n"
"3.可选取不同查看类型，如gragh（计算图）、images（输入模型的图像）"))
        self.textEdit_trainnum.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:13pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1000</p></body></html>"))
        self.Label_6.setText(_translate("MainWindow", "训练样本数量"))
        self.Label_7.setText(_translate("MainWindow", "测试样本数量"))
        self.textEdit_testnum.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:13pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">200</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "确定"))
        self.Label_name.setText(_translate("MainWindow", "手写数字识别"))
        self.Label_author.setText(_translate("MainWindow", "系统构建者\n"
"      白博\n"
"      贾晨\n"
"    吴晓锋"))
